### ISSUE TITLE
sky-progress-indicator errors

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux-progress-indicator#18]
### Expected behavior
Expect to be able to use standard structural directives (*ngFor, *ngIf, etc) on defining steps of the sky-progress-indicator

### Actual behavior
If sky-progress-indicator items are inserted via structural directives, the progress indicator renders incorrectly

### Steps to reproduce
```
<sky-progress-indicator [displayMode]="1" #progressIndicator>
      <sky-progress-indicator-item title="Configure connection">
        Content1
      </sky-progress-indicator-item>
      <sky-progress-indicator-item *ngIf="stepApplicable" title="Select remote server">
        Content2
      </sky-progress-indicator-item>
      <sky-progress-indicator-item title="Test connection">
        Content3
      </sky-progress-indicator-item>
      <sky-progress-indicator-item title="Turn on connection">
        Content4
      </sky-progress-indicator-item>
      <sky-progress-indicator-nav-button buttonType="previous" [progressIndicator]="progressIndicator">
      </sky-progress-indicator-nav-button>
      <sky-progress-indicator-nav-button buttonType="next" [progressIndicator]="progressIndicator">
      </sky-progress-indicator-nav-button>
    </sky-progress-indicator>
    <button type="button" (click)="stepApplicable=!stepApplicable">Click me</button>
```
render this html, click the 'click me' button to add the new step - note the page now has remnants of both a horizontal progress and vertical progress and displays 'undefined' for steps

### Severity
High

### Impact
Cannot use the skyux-progress-indicator in use case which include dynamic steps

**Comment by Blackbaud-AdamFunderburk** [comment]
Need to see more details about the use case here, but this is from the progress indicator guidelines:
![image](https://user-images.githubusercontent.com/15896944/56599914-92f4f300-65c5-11e9-8c63-9ffb08499811.png)

https://host.nxt.blackbaud.com/skyux/components/progress-indicator#ux-guidelines

**Comment by Blackbaud-JohnHolder** [comment]
**Totally valid point regarding the ux guidelines**, but I believe that just addresses the _design_ question of whether it is appropriate to use the component in this way, not whether it is a bug in the implementation of the component that it fails under pretty standard use.  
_IMO_, It is a bug and I believe this issue should be addressed in the component, but, at the absolute least, the component documentation should _clearly_ state that it will **fail** if used outside the narrow use case defined in the ux guidelines.  I believe it is totally possible to use this component, following the ux guidelines, and still suffer from this bug - if I build a reusable component built using the progress indicator and bound to a list of steps, even though the expected end workflow will not violate the ux guidelines, this implementation using the progress indicator will fail unless it destroys and recreates the underlying progress indicator before re-binding to a new list of steps.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
