### ISSUE TITLE
sky-progress-indicator error when attempting to hide the wizard components

### ISSUE THREAD

**Issue by BBJustCline** [blackbaud/skyux-progress-indicator#24]
### Expected behavior
When attempting to hide the wizard components from the page, we receive the exception below.  The use case is that we have a wizard for creating a custom report card, however we want to add a preview.  When they select the preview button, we are just temporarily hiding the elements on the modal and displaying the preview.  Adding the *ngIf to the div causes this to break even if we also have the *ngIf added to the nav buttons.

I attempted a work-around by adding hiding the sections inside of the <sky-progress-indicator-item element, but that has another set of issues.  It does not hide the progress indicator at the top, and it also does not seem to detect changes correctly and un-hide the nav buttons when the value is changed back to make them visible.  I tested this with only hiding one button, and the other will show up once I select the unhidden button, so the change detection seems to only work when I select one of the nav buttons.

![image](https://user-images.githubusercontent.com/53051489/61467443-9cce8e00-a949-11e9-9b9d-a7d47f004112.png)

### Steps to reproduce

Here is the snippet of code.
![image](https://user-images.githubusercontent.com/53051489/61467586-e0c19300-a949-11e9-81b1-3a748343ad39.png)

![image](https://user-images.githubusercontent.com/53051489/61467616-eb7c2800-a949-11e9-823e-d77df167a1b7.png)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.0.1`
