### ISSUE TITLE
*ngIf doesn't work correctly on sky-progress-indicator-nav-button

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-progress-indicator#29]
### Expected behavior

*ngIf correctly shows element when condition is true

### Actual behavior

Element does not show when condition is true

### Steps to reproduce

See Stackblitz: https://stackblitz.com/edit/angular-s4pa7w

**Comment by Blackbaud-SteveBrush** [comment]
Closing because the "next" and "finish" buttons are programmed to be shown/hidden automatically, based on the active index.
