### ISSUE TITLE
Wizard component doc examples reference click event for the "finish" nav button

### ISSUE THREAD

**Issue by blackbaud-james-williams** [blackbaud/skyux-progress-indicator#58]
### Expected behavior
Issue #41 was filed because the progress indicator component's "finish" nav button should use "actionClick" instead of "click". This issue references https://github.com/blackbaud/skyux2-docs/issues/917 which references https://github.com/blackbaud/skyux-progress-indicator/pull/37 which was merged. 

### Actual behavior

The example at https://developer.blackbaud.com/skyux/components/wizard still references the "click" event for the "finish" button. 

![image](https://user-images.githubusercontent.com/12701526/88398837-f014c100-cd93-11ea-8992-e7265067f9e5.png)

**Comment by Blackbaud-TrevorBurch** [comment]
This has been addressed
